### ISSUE TITLE
 Add the demo pages for dowload

### ISSUE THREAD

**Issue by lucasprogamer** [lukehaas/Scrollify#251] opened 2017-07-28 13:14 UTC
It might be interesting to see how sample pages were made, this would help some newbies :D

**Comment by MathiasHC** [comment] 2017-07-28 14:41
@lucasprogamer - you can inspect the pages and see the js. It's written in the sourcecode.

**Comment by lukehaas** [comment] 2017-08-07 08:45
Closing as this is a duplicate of #225

**Closed by lukehaas** 2017-08-07 08:45 UTC

**Comment by lucasprogamer** [comment] 2017-08-15 17:46
I' now i just think is better see in the github. :D
